version: 0.3.{build}
platform: x86
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
artifacts:
  - path: '**\*.msi'
deploy:
  release: constraintworkbench-v$(appveyor_build_version)-alpha
  provider: GitHub
  auth_token:
    secure: S4Tp4mWcK10d80w6YRHIrxrKS7x+vhJzkyyeWL5phUNKWSVKvyHcvBYdth9o8DK/ # encrypted access token from GitHub
  artifact: /.*\.msi/            # upload all installers to release assets
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
environment:
  APPVEYOR_REPO_TAG: true